In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import koreanize_matplotlib

In [6]:
df1=pd.read_csv('./기상정보_결측치처리.csv', encoding='cp949')
df2=pd.read_csv('./이상치처리(이동평균)_일별_대기오염물질배출농도.csv', encoding='utf-8')

In [7]:
df1.head()

  사업소          일자    기온     습도      풍향    풍속  강수량
0  분당  2023-01-01 -3.96  46.07  325.03  1.51  0.0
1  분당  2023-01-02 -7.45  63.39  324.52  1.44  0.0
2  분당  2023-01-03 -7.28  56.97  325.07  1.49  0.0
3  분당  2023-01-04 -5.12  68.63  324.83  1.50  0.0
4  분당  2023-01-05 -4.20  72.47  324.25  1.42  0.0

In [8]:
df2.head()

,사업소,호기,일자,SOX,NOX,먼지,산소,유량,온도,사업소_호기,NOX_대체
0,분당,1호기,2023-01-01,0.0,2.24,0.0,20.78,63.80,40.38,분당_1호기,2.24
1,분당,1호기,2023-01-02,0.0,2.87,0.0,20.85,36.01,26.45,분당_1호기,2.87
2,분당,1호기,2023-01-03,0.0,3.39,0.0,20.85,30.71,21.52,분당_1호기,3.39
3,분당,1호기,2023-01-04,0.0,10.08,0.0,18.73,27639.45,68.56,분당_1호기,10.08
4,분당,1호기,2023-01-05,0.0,12.73,0.0,15.51,59172.55,127.94,분당_1호기,12.73

In [9]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18902 entries, 0 to 18901
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   사업소     18902 non-null  object
 1   호기      18902 non-null  object
 2   일자      18902 non-null  object
 3   SOX     18902 non-null  float64
 4   NOX     18902 non-null  float64
 5   먼지      18902 non-null  float64
 6   산소      18902 non-null  float64
 7   유량      18902 non-null  float64
 8   온도      18902 non-null  float64
 9   사업소_호기  18902 non-null  object
 10  NOX_대체  18902 non-null  float64
dtypes: float64(7), object(4)
memory usage: 1.6+ MB

In [11]:
df2.groupby(['사업소', '호기']).count()

           일자  SOX  NOX   먼지   산소   유량   온도  사업소_호기  NOX_대체
사업소 호기
분당  1호기   728  728  728  728  728  728  728     728     728
    2호기   728  728  728  728  728  728  728     728     728
    3호기   727  727  727  727  727  727  727     727     727
    4호기   728  728  728  728  728  728  728     728     728
    5호기   726  726  726  726  726  726  726     726     726
    6호기   728  728  728  728  728  728  728     728     728
    7호기   728  728  728  728  728  728  728     728     728
    8호기   728  728  728  728  728  728  728     728     728
삼천포 3A호기  731  731  731  731  731  731  731     731     731
    3B호기  731  731  731  731  731  731  731     731     731
    4A호기  731  731  731  731  731  731  731     731     731
    4B호기  731  731  731  731  731  731  731     731     731
    5A호기  717  717  717  717  717  717  717     717     717
    5B호기  717  717  717  717  717  717  717     717     717
    6A호기  704  704  704  704  704  704  704     704     704
    6B호기  717  717  717  717  717  717  717     717     717
여수  -     731  731  731  731  731  731  731     731     731
    1호기   731  731  731  731  731  731  731     731     731
영동  1호기   730  730  730  730  730  730  730     730     730
    2호기   730  730  730  730  730  730  730     730     730
영흥  1호기   730  730  730  730  730  730  730     730     730
    2호기   730  730  730  730  730  730  730     730     730
    3호기   730  730  730  730  730  730  730     730     730
    4호기   730  730  730  730  730  730  730     730     730
    5호기   730  730  730  730  730  730  730     730     730
    6호기   730  730  730  730  730  730  730     730     730

## 기상정보 + 대기오염 배출물질

In [ ]:
final = pd.merge(df2, df1, how='left', on='사업소')